#include "mainwindow.h"
#include <QMouseEvent>
#include "database/databasemanager.h"
#include "database/databaseviewdialog.h"
#include "database/binaryfilehelper.h"
#include "pin/pinlistdialog.h"
#include "timeset/timesetdialog.h"
#include "timeset/filltimesetdialog.h"
#include "timeset/replacetimesetdialog.h"
#include "pin/pinvalueedit.h"
#include "vector/vectortabledelegate.h"
#include "vector/vectordatahandler.h"
#include "vector/fillvectordialog.h"
#include "vector/vector_data_types.h"
#include "common/dialogmanager.h"
#include "pin/vectorpinsettingsdialog.h"
#include "pin/pinsettingsdialog.h"
#include "vector/deleterangevectordialog.h"
#include "common/tablestylemanager.h"
#include "common/binary_file_format.h"
#include "common/utils/pathutils.h" // 修正包含路径

#include "migration/datamigrator.h"
// The compiler will merge all these files into one translation unit.
// Do NOT add these new .cpp files to your CMakeLists.txt
#include "mainwindow_setup.cpp"
#include "mainwindow_project_tables.cpp"
#include "mainwindow_pins_timeset.cpp"
#include "mainwindow_data_operations.cpp"
#include "mainwindow_dialogs_events.cpp"
#include "mainwindow_datafix_helpers.cpp"
#include "mainwindow_vector_fill.cpp"
#include "mainwindow_waveform_view.cpp"
#include "mainwindow_waveform_timeset.cpp"
