#include "mainwindow.h"
#include "database/databasemanager.h"
#include "database/databaseviewdialog.h"
#include "database/binaryfilehelper.h"
#include "pin/pinlistdialog.h"
#include "timeset/timesetdialog.h"
#include "timeset/filltimesetdialog.h"
#include "timeset/replacetimesetdialog.h"
#include "pin/pinvalueedit.h"
#include "vector/vectortabledelegate.h"
#include "vector/vectordatahandler.h"
#include "vector/fillvectordialog.h"
#include "vector/vector_data_types.h"
#include "common/dialogmanager.h"
#include "pin/vectorpinsettingsdialog.h"
#include "pin/pinsettingsdialog.h"
#include "vector/deleterangevectordialog.h"
#include "common/tablestylemanager.h"
#include "common/binary_file_format.h"
#include "common/utils/pathutils.h" // 修正包含路径

#include <QMenuBar>
#include <QMenu>
#include <QAction>
#include <QApplication>
#include <QStandardPaths>
#include <QSqlQuery>
#include <QSqlError>
#include <QSqlRecord>
#include <QHeaderView>
#include <QVBoxLayout>
#include <QLabel>
#include <QDebug>
#include <QStatusBar>
#include <QHBoxLayout>
#include <QPushButton>
#include <QTableWidgetItem>
#include <QFont>
#include <QStyledItemDelegate>
#include <QComboBox>
#include <QCheckBox>
#include <QGridLayout>
#include <QGroupBox>
#include <QFormLayout>
#include <QLineEdit>
#include <QKeyEvent>
#include <QIcon>
#include <QFileInfo>
#include <QDialogButtonBox>
#include <QInputDialog>
#include <QSpinBox>
#include <QScrollArea>
#include <QTimer>
#include <QListWidget>
#include <QListWidgetItem>
#include <QDir>
#include <QFile>
#include <QDateTime>
#include <QSplitter>
#include <QSizePolicy>
#include <QSettings>
#include <QCloseEvent>
#include <QJsonDocument>
#include <QJsonObject>
#include <QJsonParseError>
#include <QToolBar>
#include <QToolButton>
#include <QVariant>
#include <QProgressDialog>
#include <QTreeView>
#include <QStandardItemModel>

#include "migration/datamigrator.h"
// The compiler will merge all these files into one translation unit.
// Do NOT add these new .cpp files to your CMakeLists.txt
#include "mainwindow_setup.cpp"
#include "mainwindow_project_tables.cpp"
#include "mainwindow_pins_timeset.cpp"
#include "mainwindow_data_operations.cpp"
#include "mainwindow_dialogs_events.cpp"
#include "mainwindow_datafix_helpers.cpp"
#include "mainwindow_vector_fill.cpp"