#ifndef VERSION_H
#define VERSION_H

// Version components defined by CMake from project(VERSION ...)
#define VECEDIT_VERSION_MAJOR 0
#define VECEDIT_VERSION_MINOR 6
#define VECEDIT_VERSION_PATCH 2
#define VECEDIT_VERSION_TWEAK 289

// Full version string e.g., "0.0.0.3"
#define VECEDIT_VERSION_STRING "0.6.2.289"

// Helper macros to stringify version components
#define VECEDIT_VERSION_TO_STRING_HELPER(x) #x
#define VECEDIT_VERSION_TO_STRING(x) VECEDIT_VERSION_TO_STRING_HELPER(x)

// Detailed full version string, e.g., "0.0.0.2", constructed from components
#define VECEDIT_FULL_VERSION_STRING VECEDIT_VERSION_TO_STRING(VECEDIT_VERSION_MAJOR) "." VECEDIT_VERSION_TO_STRING(VECEDIT_VERSION_MINOR) "." VECEDIT_VERSION_TO_STRING(VECEDIT_VERSION_PATCH) "." VECEDIT_VERSION_TO_STRING(VECEDIT_VERSION_TWEAK)

#endif // VERSION_H
